services:
  db:
    ports: [5432:5432]
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=midas
      - POSTGRES_USER=midas
      - POSTGRES_DB=midas
    healthcheck:
      test:
        - "CMD-SHELL"
        - "sh -c 'pg_isready -d midas -U midas'"
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s
